### ISSUE TITLE
Transaction Error: Missing Required Active Authority

### ISSUE THREAD

**Issue by cadawg** [t3ran13/php-graphene-node-client#19]
Hello, I have been attempting to use your client to send transactions via PHP, but upon trying to commit it, it tells me that it is missing the active authority, even though I have checked and double checked my active key, and it definitely is correct!

I am running: 
Ubuntu 16.04.3 LTS on WSSL

PHP 7.0.32

https://github.com/Bit-Wasp/secp256k1-php - Version 2.1

automake, libtool and libgmp-dev are all installed and GMP is working.

```
<?php

require "vendor/t3ran13/php-graphene-node-client/Tools/ChainOperations/OpTransfer.php";
require "vendor/autoload.php";

use GrapheneNodeClient\Connectors\Http\SteemitHttpJsonRpcConnector;
use GrapheneNodeClient\Tools\ChainOperations\OpTransfer;


$connector = new SteemitHttpJsonRpcConnector();

$opdoer = new OpTransfer();

$opdoer->doSynchronous($connector,"MY PRIVATE ACTIVE KEY","cadawg","cadawg","0.001 STEEM","Test PHP Graphene");
```

And upon running the above code (with active key substituted), I get the following error:

```
PHP Fatal error:  Uncaught Exception: got error in answer: -32000 missing required active authority:Missing Active Authority cadawg in /home/conor/steemsend/vendor/t3ran13/php-graphene-node-client/Connectors/Http/HttpJsonRpcConnectorAbstract.php:243
Stack trace:
#0 /home/conor/steemsend/vendor/t3ran13/php-graphene-node-client/Connectors/Http/HttpJsonRpcConnectorAbstract.php(259): GrapheneNodeClient\Connectors\Http\HttpJsonRpcConnectorAbstract->doRequest('network_broadca...', Array, 'array', 3, false)
#1 /home/conor/steemsend/vendor/t3ran13/php-graphene-node-client/Connectors/Http/HttpJsonRpcConnectorAbstract.php(259): GrapheneNodeClient\Connectors\Http\HttpJsonRpcConnectorAbstract->doRequest('network_broadca...', Array, 'array', 2, false)
#2 /home/conor/steemsend/vendor/t3ran13/php-graphene-node-client/Connectors/Http/HttpJsonRpcConnectorAbstract.php(264): GrapheneNodeClient\Connectors\Http\HttpJsonRpcConnectorAbstract->doRequest('network_broadca...', Array, 'array', 1, false)
#3 /home/conor/steemsend/vendor/t3ran13/php-graphe in /home/conor/steemsend/vendor/t3ran13/php-graphene-node-client/Connectors/Http/HttpJsonRpcConnectorAbstract.php on line 243
```

Thanks,
Conor

**Comment by t3ran13** [comment]
try install all like here
https://github.com/t3ran13/php-graphene-node-client/blob/debug/docker/local/dockerfile-php7-fpm

**Comment by t3ran13** [comment]
it works correct
https://steemd.com/b/26850947#3eebe79d5ba6e6d4a768d63e071aa652ee966988
